---
name: Demo
on:
  push:
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: ojab/ssh-agent@master
        with:
          ssh-private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACD+XmCil8wo0NS+GpYwQksl+S5obx7CcWnADY2opH1BlwAAAIia4jhBmuI4
            QQAAAAtzc2gtZWQyNTUxOQAAACD+XmCil8wo0NS+GpYwQksl+S5obx7CcWnADY2opH1Blw
            AAAECt09sH8gaT33WqwpqIsuWNKc+3/OsPR1aAEcuMQY6Ltf5eYKKXzCjQ1L4aljBCSyX5
            LmhvHsJxacANjaikfUGXAAAABWZpcnN0
            -----END OPENSSH PRIVATE KEY-----
      - run: ssh-add -l
      - name: Setup SSH
        uses: ojab/ssh-agent@master
        with:
          ssh-private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACBFCNU7Y6tGKWwwXud1Tz9Q0o/46WRFRDjS3Hz6VB5ZJQAAAJDiatrU4mra
            1AAAAAtzc2gtZWQyNTUxOQAAACBFCNU7Y6tGKWwwXud1Tz9Q0o/46WRFRDjS3Hz6VB5ZJQ
            AAAEBV1TkpoS01BHgYuHAGS3lv9OkELT+25VIv9Ta102PztkUI1Ttjq0YpbDBe53VPP1DS
            j/jpZEVEONLcfPpUHlklAAAABnNlY29uZAECAwQFBgc=
            -----END OPENSSH PRIVATE KEY-----
      - run: ssh-add -l

  docker_demo:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - run: apt update && apt install -y openssh-client git
      - name: Setup SSH
        uses: ojab/ssh-agent@master
        with:
          ssh-private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACD+XmCil8wo0NS+GpYwQksl+S5obx7CcWnADY2opH1BlwAAAIia4jhBmuI4
            QQAAAAtzc2gtZWQyNTUxOQAAACD+XmCil8wo0NS+GpYwQksl+S5obx7CcWnADY2opH1Blw
            AAAECt09sH8gaT33WqwpqIsuWNKc+3/OsPR1aAEcuMQY6Ltf5eYKKXzCjQ1L4aljBCSyX5
            LmhvHsJxacANjaikfUGXAAAABWZpcnN0
            -----END OPENSSH PRIVATE KEY-----
      - run: ssh-add -l
      - name: Setup SSH
        uses: ojab/ssh-agent@master
        with:
          ssh-private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACBFCNU7Y6tGKWwwXud1Tz9Q0o/46WRFRDjS3Hz6VB5ZJQAAAJDiatrU4mra
            1AAAAAtzc2gtZWQyNTUxOQAAACBFCNU7Y6tGKWwwXud1Tz9Q0o/46WRFRDjS3Hz6VB5ZJQ
            AAAEBV1TkpoS01BHgYuHAGS3lv9OkELT+25VIv9Ta102PztkUI1Ttjq0YpbDBe53VPP1DS
            j/jpZEVEONLcfPpUHlklAAAABnNlY29uZAECAwQFBgc=
            -----END OPENSSH PRIVATE KEY-----
      - run: ssh-add -l
